# Generated by Django 5.0.6 on 2024-05-23 12:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bracket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level_from",
                    models.DecimalField(decimal_places=1, default=1, max_digits=2),
                ),
                (
                    "level_to",
                    models.DecimalField(decimal_places=1, default=2, max_digits=2),
                ),
                ("name", models.CharField(default="Bracket", max_length=100)),
                ("max_teams", models.IntegerField(default=8)),
            ],
            options={
                "verbose_name": "Række",
                "verbose_name_plural": "Rækker",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Padel Lounge",
                        max_length=200,
                        unique=True,
                        verbose_name="Navn",
                    ),
                ),
                ("address", models.CharField(max_length=200, verbose_name="Addresse")),
                ("city", models.CharField(max_length=200, verbose_name="By")),
                (
                    "zip_code",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1000),
                            django.core.validators.MaxValueValidator(9999),
                        ],
                        verbose_name="Postnummer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lokation",
                "verbose_name_plural": "Lokationer",
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1)),
                (
                    "bracket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="tournament.bracket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gruppe",
                "verbose_name_plural": "Grupper",
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player1", models.CharField(max_length=200)),
                ("player2", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=200)),
                ("phone", models.CharField(max_length=200)),
                ("paid", models.BooleanField(default=False)),
                (
                    "bracket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="tournament.bracket",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="tournament.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hold",
                "verbose_name_plural": "Hold",
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_finale", models.BooleanField(default=False)),
                ("team1_set1", models.IntegerField(default=0, verbose_name="Sæt 1")),
                ("team1_set2", models.IntegerField(default=0, verbose_name="Sæt 2")),
                ("team1_set3", models.IntegerField(default=0, verbose_name="Sæt 3")),
                ("team2_set1", models.IntegerField(default=0, verbose_name="Sæt 1")),
                ("team2_set2", models.IntegerField(default=0, verbose_name="Sæt 2")),
                ("team2_set3", models.IntegerField(default=0, verbose_name="Sæt 3")),
                ("team1_points", models.IntegerField(default=0)),
                ("team2_points", models.IntegerField(default=0)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("track_number", models.IntegerField(blank=True, null=True)),
                (
                    "bracket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="tournament.bracket",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="tournament.group",
                    ),
                ),
                (
                    "loser",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lost_matches",
                        to="tournament.team",
                    ),
                ),
                (
                    "loser_set1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lost_set1",
                        to="tournament.team",
                    ),
                ),
                (
                    "loser_set2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lost_set2",
                        to="tournament.team",
                    ),
                ),
                (
                    "loser_set3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lost_set3",
                        to="tournament.team",
                    ),
                ),
                (
                    "team1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_matches",
                        to="tournament.team",
                    ),
                ),
                (
                    "team2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="away_matches",
                        to="tournament.team",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="won_matches",
                        to="tournament.team",
                    ),
                ),
                (
                    "winner_set1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="won_set1",
                        to="tournament.team",
                    ),
                ),
                (
                    "winner_set2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="won_set2",
                        to="tournament.team",
                    ),
                ),
                (
                    "winner_set3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="won_set3",
                        to="tournament.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kamp",
                "verbose_name_plural": "Kampe",
            },
        ),
        migrations.AddField(
            model_name="group",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="won_groups",
                to="tournament.team",
            ),
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Fredagsturnering Juni 2024 Aalborg",
                        max_length=200,
                        unique=True,
                        verbose_name="Navn",
                    ),
                ),
                ("date", models.DateField(verbose_name="Dato")),
                (
                    "start_time",
                    models.TimeField(default="16:00:00", verbose_name="Start"),
                ),
                ("end_time", models.TimeField(default="23:59:59", verbose_name="Slut")),
                ("tracks", models.IntegerField(default=6, verbose_name="Antal Baner")),
                (
                    "location",
                    models.ForeignKey(
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.location",
                        verbose_name="Lokation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Turnering",
                "verbose_name_plural": "Turneringer",
                "ordering": ["date"],
            },
        ),
        migrations.AddField(
            model_name="bracket",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brackets",
                to="tournament.tournament",
            ),
        ),
    ]
